### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by mnmr** [bmbsqd/AsyncLock#1]

**Comment by icanhasjonas** [comment]
I'll add preliminary support now. 

It's almost Friday, so why not!

**Comment by icanhasjonas** [comment]
Initial corification available now under the [core](https://github.com/bmbsqd/AsyncLock/tree/core) branch

**Comment by mnmr** [comment]
That was quick - thanks!

**Comment by icanhasjonas** [comment]
Sure, np, it's on nuget as of today as well
https://www.nuget.org/packages/Bmbsqd.AsyncLock/
